"""added about_me and last_seen fields to User model

Revision ID: 1731ce4d9364
Revises: 8acd23a95fc1
Create Date: 2022-04-03 14:45:58.205726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1731ce4d9364'
down_revision = '8acd23a95fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
